using System;
public class GrandPianoController
{

    public static string[] GetSounds()
    {
        if (EasyModeButtonController.IsButtonPressed() && ShowKeysButtonController.IsButtonPressed())
        {
            if (EasyModeButtonController.IsEasyModeLocatedLeft())
            {
                return new string[] { "Sounds/GrandPiano/C1",
                                      "Sounds/GrandPiano/D1",
                                      "Sounds/GrandPiano/E1",
                                      "Sounds/GrandPiano/F1",
                                      "Sounds/GrandPiano/G1",
                                      "Sounds/GrandPiano/A1",
                                      "Sounds/GrandPiano/B1",
                                      "Sounds/GrandPiano/C2",
                                      "Sounds/GrandPiano/D2",
                                      "Sounds/GrandPiano/E2",
                                      "Sounds/GrandPiano/F2",
                                      "Sounds/GrandPiano/G2",
                                      "Sounds/GrandPiano/A2",
                                      "Sounds/GrandPiano/B2",
                                      "Sounds/GrandPiano/C3",
                                      "Sounds/GrandPiano/D3",
                                      "Sounds/GrandPiano/E3",
                                      "Sounds/GrandPiano/F3",
                                      "Sounds/GrandPiano/G3",
                                      "Sounds/GrandPiano/A3",
                                      "Sounds/GrandPiano/B3",
                                      "Sounds/GrandPiano/C4",
                                      "Sounds/GrandPiano/C#1",
                                      "Sounds/GrandPiano/D#1",
                                      "Sounds/GrandPiano/F#1",
                                      "Sounds/GrandPiano/G#1",
                                      "Sounds/GrandPiano/A#1",
                                      "Sounds/GrandPiano/C#2",
                                      "Sounds/GrandPiano/D#2",
                                      "Sounds/GrandPiano/F#2",
                                      "Sounds/GrandPiano/G#2",
                                      "Sounds/GrandPiano/A#2",
                                      "Sounds/GrandPiano/C#3",
                                      "Sounds/GrandPiano/D#3",
                                      "Sounds/GrandPiano/F#3",
                                      "Sounds/GrandPiano/G#3",
                                      "Sounds/GrandPiano/A#3"};
            }
            else if (EasyModeButtonController.IsEasyModeLocatedRight())
            {
                return new string[] { "Sounds/GrandPiano/C3",
                                      "Sounds/GrandPiano/D3",
                                      "Sounds/GrandPiano/E3",
                                      "Sounds/GrandPiano/F3",
                                      "Sounds/GrandPiano/G3",
                                      "Sounds/GrandPiano/A3",
                                      "Sounds/GrandPiano/B3",
                                      "Sounds/GrandPiano/C4",
                                      "Sounds/GrandPiano/D4",
                                      "Sounds/GrandPiano/E4",
                                      "Sounds/GrandPiano/F4",
                                      "Sounds/GrandPiano/G4",
                                      "Sounds/GrandPiano/A4",
                                      "Sounds/GrandPiano/B4",
                                      "Sounds/GrandPiano/C5",
                                      "Sounds/GrandPiano/D5",
                                      "Sounds/GrandPiano/E5",
                                      "Sounds/GrandPiano/F5",
                                      "Sounds/GrandPiano/G5",
                                      "Sounds/GrandPiano/A5",
                                      "Sounds/GrandPiano/B5",
                                      "Sounds/GrandPiano/C6",
                                      "Sounds/GrandPiano/C#3",
                                      "Sounds/GrandPiano/D#3",
                                      "Sounds/GrandPiano/F#3",
                                      "Sounds/GrandPiano/G#3",
                                      "Sounds/GrandPiano/A#3",
                                      "Sounds/GrandPiano/C#4",
                                      "Sounds/GrandPiano/D#4",
                                      "Sounds/GrandPiano/F#4",
                                      "Sounds/GrandPiano/G#4",
                                      "Sounds/GrandPiano/A#4",
                                      "Sounds/GrandPiano/C#5",
                                      "Sounds/GrandPiano/D#5",
                                      "Sounds/GrandPiano/F#5",
                                      "Sounds/GrandPiano/G#5",
                                      "Sounds/GrandPiano/A#5"};
            }
            else // IsEasyModeLocatedMiddle
            {
                return new string[] { "Sounds/GrandPiano/C2",
                                      "Sounds/GrandPiano/D2",
                                      "Sounds/GrandPiano/E2",
                                      "Sounds/GrandPiano/F2",
                                      "Sounds/GrandPiano/G2",
                                      "Sounds/GrandPiano/A2",
                                      "Sounds/GrandPiano/B2",
                                      "Sounds/GrandPiano/C3",
                                      "Sounds/GrandPiano/D3",
                                      "Sounds/GrandPiano/E3",
                                      "Sounds/GrandPiano/F3",
                                      "Sounds/GrandPiano/G3",
                                      "Sounds/GrandPiano/A3",
                                      "Sounds/GrandPiano/B3",
                                      "Sounds/GrandPiano/C4",
                                      "Sounds/GrandPiano/D4",
                                      "Sounds/GrandPiano/E4",
                                      "Sounds/GrandPiano/F4",
                                      "Sounds/GrandPiano/G4",
                                      "Sounds/GrandPiano/A4",
                                      "Sounds/GrandPiano/B4",
                                      "Sounds/GrandPiano/C5",
                                      "Sounds/GrandPiano/C#2",
                                      "Sounds/GrandPiano/D#2",
                                      "Sounds/GrandPiano/F#2",
                                      "Sounds/GrandPiano/G#2",
                                      "Sounds/GrandPiano/A#2",
                                      "Sounds/GrandPiano/C#3",
                                      "Sounds/GrandPiano/D#3",
                                      "Sounds/GrandPiano/F#3",
                                      "Sounds/GrandPiano/G#3",
                                      "Sounds/GrandPiano/A#3",
                                      "Sounds/GrandPiano/C#4",
                                      "Sounds/GrandPiano/D#4",
                                      "Sounds/GrandPiano/F#4",
                                      "Sounds/GrandPiano/G#4",
                                      "Sounds/GrandPiano/A#4"};
            }

        }
        else
        {
            return GetAllSounds();
        }
    }

    public static string[] GetAllSounds()
    {

         return new string[] {  ("Sounds/GrandPiano/C1"),
                                ("Sounds/GrandPiano/C2"),
                                ("Sounds/GrandPiano/C3"),
                                ("Sounds/GrandPiano/C4"),
                                ("Sounds/GrandPiano/C5"),
                                ("Sounds/GrandPiano/C6"),
                                ("Sounds/GrandPiano/D1"),
                                ("Sounds/GrandPiano/D2"),
                                ("Sounds/GrandPiano/D3"),
                                ("Sounds/GrandPiano/D4"),
                                ("Sounds/GrandPiano/D5"),
                                ("Sounds/GrandPiano/E1"),
                                ("Sounds/GrandPiano/E2"),
                                ("Sounds/GrandPiano/E3"),
                                ("Sounds/GrandPiano/E4"),
                                ("Sounds/GrandPiano/E5"),
                                ("Sounds/GrandPiano/F1"),
                                ("Sounds/GrandPiano/F2"),
                                ("Sounds/GrandPiano/F3"),
                                ("Sounds/GrandPiano/F4"),
                                ("Sounds/GrandPiano/F5"),
                                ("Sounds/GrandPiano/G1"),
                                ("Sounds/GrandPiano/G2"),
                                ("Sounds/GrandPiano/G3"),
                                ("Sounds/GrandPiano/G4"),
                                ("Sounds/GrandPiano/G5"),
                                ("Sounds/GrandPiano/A1"),
                                ("Sounds/GrandPiano/A2"),
                                ("Sounds/GrandPiano/A3"),
                                ("Sounds/GrandPiano/A4"),
                                ("Sounds/GrandPiano/A5"),
                                ("Sounds/GrandPiano/B1"),
                                ("Sounds/GrandPiano/B2"),
                                ("Sounds/GrandPiano/B3"),
                                ("Sounds/GrandPiano/B4"),
                                ("Sounds/GrandPiano/B5"),
                                ("Sounds/GrandPiano/C#1"),
                                ("Sounds/GrandPiano/C#2"),
                                ("Sounds/GrandPiano/C#3"),
                                ("Sounds/GrandPiano/C#4"),
                                ("Sounds/GrandPiano/C#5"),
                                ("Sounds/GrandPiano/D#1"),
                                ("Sounds/GrandPiano/D#2"),
                                ("Sounds/GrandPiano/D#3"),
                                ("Sounds/GrandPiano/D#4"),
                                ("Sounds/GrandPiano/D#5"),
                                ("Sounds/GrandPiano/F#1"),
                                ("Sounds/GrandPiano/F#2"),
                                ("Sounds/GrandPiano/F#3"),
                                ("Sounds/GrandPiano/F#4"),
                                ("Sounds/GrandPiano/F#5"),
                                ("Sounds/GrandPiano/G#1"),
                                ("Sounds/GrandPiano/G#2"),
                                ("Sounds/GrandPiano/G#3"),
                                ("Sounds/GrandPiano/G#4"),
                                ("Sounds/GrandPiano/G#5"),
                                ("Sounds/GrandPiano/A#1"),
                                ("Sounds/GrandPiano/A#2"),
                                ("Sounds/GrandPiano/A#3"),
                                ("Sounds/GrandPiano/A#4"),
                                ("Sounds/GrandPiano/A#5")};
    }



}

